swagger: "2.0"
info:
  description: "reudのポートフォリオサイトのバックエンドAPI"
  version: "0.0.1"
  title: "portal.reud.net API"
  termsOfService: "TODO"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "TODO"
basePath: "/"
tags:
  - name: "bookshelf"
    description: "本棚機能に関連したもの"

schemes:
  - "https"
  - "http"
paths:
  /bookshelf:
    post:
      tags:
        - "bookshelf"
      summary: "Add a new book to bookshelf"
      description: "amazonの本を投稿できる機能(amazonにあるもの)"
      operationId: "addReudBook"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "本の情報は本棚に登録するために必要である。"
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
        401:
          description: "Unauthorized"
        400:
          description: "Bad Request"
  /bookshelf/{bookId}:
    delete:
      tags:
        - "bookshelf"
      summary: "delete book by id"
      description: "amazonの投稿した本を削除する機能"
      operationId: "deleteReudBook"
      parameters:
        - name: "bookId"
          in: "path"
          description: "Bookのid"
          required: true
          type: "integer"
          format: "int64"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
        401:
          description: "Unauthorized"
definitions:
  Book:
    type: "object"
    required:
      - "title"
      - "href"
      - "imageSource"
      - "tag1"
    properties:
      title:
        type: "string"
        example: "Book Title"
      href:
        type: "string"
        example: "https://www.amazon.co.jp/"
      imageSource:
        type: "string"
        example: "https://ir-jp.amazon-adsystem.com/e/ir"
      tag1:
        type: "string"
        example: "manga"
      tag2:
        type: "string"
        example: "tech"
      tag3:
        type: "string"
        example: "C++"
