swagger: "2.0"
info:
  description: "reudのポートフォリオサイトのバックエンドAPI"
  version: "0.0.1"
  title: "portal.reud.net API"
  termsOfService: "TODO"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8000"
basePath: "/api"
tags:
  - name: "bookshelf"
    description: "本棚機能に関連したもの"

schemes:
  - "http"
  - "https"
paths:
  /bookshelf:
    get:
      tags:
        - "bookshelf"
      summary: "Get books I read, from DB"
      description: "DBに保存された本の情報の取得"
      operationId: "getReudBook"
      consumes:
        - "application/json"
      responses:
        200:
          description: "本の情報、IDはreudが本を同サイトから消す際に使用される。"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        500:
          description: "Internal Server Error"

    post:
      tags:
        - "bookshelf"
      summary: "Add a new book to bookshelf"
      description: "amazonの本を投稿できる機能(amazonにあるもの)"
      operationId: "addReudBook"
      security:
        - auth0Auth: []
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "本の情報は本棚に登録するために必要である。"
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
        401:
          description: "Unauthorized"
        400:
          description: "Bad Request"
  /bookshelf/{bookId}:
    delete:
      tags:
        - "bookshelf"
      summary: "delete book by id"
      description: "amazonの投稿した本を削除する機能"
      operationId: "deleteReudBook"
      security:
        - auth0Auth: []
      parameters:
        - name: "bookId"
          in: "path"
          description: "Bookのid"
          required: true
          type: "integer"
          format: "int64"
      responses:
        204:
          description: "No Content"
        500:
          description: "Internal Server Error"
        401:
          description: "Unauthorized"
definitions:
  Book:
    type: "object"
    required:
      - "title"
      - "href"
      - "wsfeImageSource"
      - "irjpImageSource"
      - "tag1"
    properties:
      ID:
        type: "integer"
        example: "24"
      title:
        type: "string"
        example: "Book Title"
      href:
        type: "string"
        example: "https://www.amazon.co.jp/"
      wsfeImageSource:
        type: "string"
        example: "//ws-fe.amazon-adsystem.com/widgets/q"
      irjpImageSource:
        type: "string"
        example: "https://ir-jp.amazon-adsystem.com/e/ir"
      tag1:
        type: "string"
        example: "manga"
      tag2:
        type: "string"
        example: "tech"
      tag3:
        type: "string"
        example: "C++"
securityDefinitions:
  auth0Auth:
    type: "apiKey"
    in: "header"
    name: "Authorization"

